title: Frank Bi
baseURL: "https://reorx.github.io/biwentao/"
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

params:
  description: "Frank Bi description"
  author: Reorx
  images:
    - cover.png
  favicon: favicon.ico
  #logo:
  #  icon: images/logo.svg
  DateFormat: "2006-01-02"
  useCustomAnalytics: true
  mainSections:
    - posts
    - notes

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
    - linkedin
    - reddit
    - facebook
    - whatsapp
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  Email: biwentaofrank@gmail.com

  socialIcons:
    - name: github-simple
      url: "https://github.com/wentaobi"
    - name: twitter-simple
      url: "https://twitter.com/bi_wentao"
    - name: rss-simple
      url: "feed.xml"
    - name: gmail
      url: biwentaofrank@gmail.com
    - name: linkedin-simple
      url: https://www.linkedin.com/in/wentaobi
    - name: qq
      url: 649549603@qq.com
    - name: facebook-simple
      url: https://www.facebook.com/wentao.bi.3
    - name: bilibili
      url: https://space.bilibili.com/435665051
    - name: external-link
      url: https://www.1point3acres.com/bbs/
    - name: slack
      url: https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite
    - name: medium
      url: https://www.zhihu.com/people/biwentaofrank
    - name: hackerrank
      url: https://leetcode.com/biwentaofrank/

  socialAccounts:
    twitter:
      username: bi_wentao

  homeInfoParams:
    Title: "Get Ready With Me" 
    Content: |
      Hi, I'm your Frank. You visit me at {{< time.inline >}}{{ now }}{{< /time.inline >}}  

      <p><span class="nowrap"><span class="emojify">🙈</span>  <span class="nowrap"><span class="emojify">🙉</span>  <span class="nowrap"><span class="emojify">🙊</span></span></p>

      - I'm a software engineer, I'm interested in Embedded software, Autonomous system, Machine learning compiler.

      - In my spare time, I like Fitness, Road Trip, Good movies, Poker.

      I will update this blog for daily life recording, such as work, life, study, etc.

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Notes
      url: /notes/
      weight: 2
    - name: Newsletter
      url: /newsletter/
      weight: 3
    - name: Archives
      url: /archives/
      weight: 4

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
